fix: refactor CLI options (WIP)
optopodi/optopodi pull request #35
Opened 2021-06-22 18:31 UTC by chazkiker2

## Description

- [ ] closes #26

2021-06-22 19:30 UTC, chazkiker2 commented
WIP — I think my GitHub rate is cached for the moment

2021-06-22 19:42 UTC, nikomatsakis requested changes

2021-06-22 19:42 UTC, nikomatsakis commented on src/main.rs
> +    if cli.print {
```suggestion
    else if cli.print {
```

we only do one or the other, right?

2021-06-23 08:21 UTC, nikomatsakis commented on src/main.rs
> +    if cli.print {
Actually, maybe we should set things up so that there is an intermediate layer, and you can expert in multiple ways?

2021-06-23 08:26 UTC, nikomatsakis commented
I know this is not totally done, @chazkiker2, but I kind of want these changes so I'm going to land it anyway. :)

2021-06-23 08:27 UTC, merged