Add Collaboration Guidelines to Contribution Guide
optopodi/optopodi pull request #59
Opened 2021-07-08 17:28 UTC by doc-jones

Include guidelines adopted from Mentored Sprints and The Recurse Center's Social Rules.  Some editorial freedoms applied.

2021-07-08 17:30 UTC, nikomatsakis requested changes
Looks good, one minor nit

2021-07-08 17:30 UTC, nikomatsakis commented on book/src/contributing.md
> +```
I think I would rather have this be a "bullet list" in markdown than a code block

2021-07-08 17:30 UTC, nikomatsakis commented on book/src/contributing.md
> +**And finally, not every comment requires a response.**
+1

2021-07-08 17:59 UTC, chazkiker2 commented on book/src/contributing.md
> +* eing respectful of differing viewpoints and experiences
SP: can we correct "eing" to "Being"?

2021-07-08 18:21 UTC, doc-jones commented on book/src/contributing.md
> +* eing respectful of differing viewpoints and experiences
Add a B

2021-07-08 19:47 UTC, nikomatsakis requested changes

2021-07-08 19:47 UTC, nikomatsakis commented on book/src/contributing.md
> +* Examples of unacceptable behaviour by participants include:
```suggestion

Examples of unacceptable behaviour by participants include:
```

2021-07-09 10:13 UTC, nikomatsakis commented
bors r+

2021-07-09 10:17 UTC, merged